mysite/food/urls.py
from . import views
from django.urls import path

# define namespace for urls
app_name='food'

urlpatterns = [
    #/food/
    path("", views.index, name='index'), 
    #/food/id
    path("<int:product_id>", views.info, name='info'), 
    
    path("product/", views.product, name='product'), 
    path('add', views.create_product, name='create_product'),
    # edit 
    path('update/<int:id>/', views.update_product, name='update_product'),
    
    path("delete/<int:id>/", views.delete_product, name='delete_product')
] 

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls', namespace='food')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', user_views.logout_view, name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
    # path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout')
]

# Serving static files during development
# add url patterns for static files uploaded by the user 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Add this line

mysite/food/models.py
from django.db import models

# Create your models here. 

# produt model for db
class Product(models.Model):
    product_name = models.CharField(max_length=200)
    product_doc = models.CharField(max_length=200)
    product_price = models.IntegerField()
    product_image = models.CharField(max_length=500, default="https://t4.ftcdn.net/jpg/03/76/40/81/360_F_376408140_kiazgwOvkEy0e50oxgF5kllIl7j2q1SQ.jpg")
    
    
    # string representation of an object 
    def __str__(self):
        return self.product_name
    
    
    
    
    
    
    
    

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE )             #associate the user with the profile model
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username 
    
    

mysite/food/forms.py
from django import forms 
from .models import Product

# product form class to add items
class ProductForm(forms.ModelForm):             #inherit from the ModelForm 
    class Meta:         #class that holds the fields should be in the form 
        model = Product         #set the model the form will use 
        fields = ['product_name','product_doc','product_price','product_image']
        
        
        

mysite/users/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm

# create register form to inherit from the user creation form
class RegisterForm(UserCreationForm):
    email = forms.EmailField()                  #add additional field 
    
    # define meta class - hold info about register form 
    class Meta:
        model = User
        fields = ['username','email','password1','password2'] 
    

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product
from django.template import loader 
from .forms import ProductForm


# Create your views here.
def index(request):
    # get objects from database
    productList = Product.objects.all()             #get all products andd save in product list 
    template = loader.get_template('food/index.html')               #lost the home page 
    context = {'productList':productList}               #initialized the context 
    return HttpResponse(template.render(context, request))                            

# product page view
def product(request):
    return HttpResponse('<h1>Product Page</h1>')
    
def info(request, product_id):
    product = Product.objects.get(pk=product_id)                #get product based on the id 
    context = {'productList':product}
    return render(request, "food/info.html", context)
    # return HttpResponse("This is produt no/id: %s"  % product_id) 
    
    
    # view for add product form 
def create_product(request):
    # get form 
    form = ProductForm(request.POST or None)            #create product object using post request or none 
    
    if form.is_valid():              #check if the form is valid 
        form.save()             #save the form
        return redirect('food:index')                   #redirect to the homepage 
    return render(request, "food/product-form.html", {"form":form})             #display the product form page 

    
    # view for update product form 
def update_product(request, id):
    product = Product.objects.get(id=id)            #get object based on id     
    form = ProductForm(request.POST or None, instance=product)              #create form object and pass product data to form 
    
    
    if form.is_valid():             #save form if valid 
        form.save()
        
        return redirect('food:index')               #redirect to index page 
    return render(request, 'food/product-form.html', {'form':form, 'product':product})              #

    # view to delete a product
def delete_product(request, id):
    product = Product.objects.get(id=id)            #get id of object to delete 
    
    # if request request is podt delete the item
    if request.method == "POST":
        product.delete()
        return redirect('food:index')
    
    return render(request, "food/product-delete.html", {'product':product})
    
    
    
    
    

mysite/users/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required 
from .forms import RegisterForm
from django.contrib.auth import logout

# Create your views here.

def register(request):
    if request.method == "POST":                #if request method for the form is post 
        
        
        # form = UserCreationForm(request.POST)
        form = RegisterForm(request.POST)               #save register form post request
        
        if form.is_valid():             #if the form is valid display a message
            form.save()                 #save the user 
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, your account is created' )
            # redirect user to index page
            return redirect('login')
    else:
        # form = UserCreationForm()               #store user creation form in the form 
        form = RegisterForm()                 
        
    return render(request, 'users/register.html', {'form':form})                #


def logout_view(request):
    logout(request)
  
    return render(request, 'users/logout.html')

@login_required
def profilepage(request):
    username = request.user.username
    user = request.user
    context = {'username': username, 'user':user }
    return render(request, 'users/profile.html', context)

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <style>
    #viewproduct {
      margin-right: 20px;
    }
    #na-bottom {
      margin-bottom: 20px;
    }
  </style>

  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between"
      id="na-bottom"
    >
      <a class="navbar-brand me-3" href="#">FoodApp</a>
      <div class="d-flex">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'food:create_product' %}"
              >Add Product</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Delete Product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">View Product</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
          </li>
          {% endif %}
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a id="viewproduct" class="nav-link" href="{% url 'login' %}"
              >Login</a
            >
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
    {% if messages %} {% for message in messages %}
    <div class="alert" alert-{{ message.tag }}>{{ message }}</div>
    {% endfor %} {% endif %} {% block body %} {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

mysite/food/templates/food/index.html
{% extends 'food/base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>My Web Page</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </head>

  <body>
    <!-- As a heading -->
    {% block body %} {% for product in productList %}

    <div class="row">
      <div class="col-md-3 offset-md-2">
        <img class="card" , height="150px" , src="{{ product.product_image}}" />
      </div>
      <div class="col-md-4">
        <h3>{{ product.product_name }}</h3>
        <h5>{{ product.product_doc}}</h5>
        <h6>${{ product.product_price }}</h6>
      </div>
      <div class="col-md-2">
        <a href="{% url 'food:info' product.id %}" class="btn btn-success"
          >Info</a
        >
      </div>
    </div>

    {% endfor %} {% endblock %}
  </body>
</html>

mysite/food/templates/food/info.html
{% extends 'food/base.html' %} {% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img height="300px" src="{{productList.product_image}}" class="card" />
    </div>

    <div class="col-md-6">
      <h1>{{ productList.product_name }}</h1>
      <h2>{{ productList.product_doc}}</h2>
      <h2>${{ productList.product_price}}</h2>
      <a href="{% url 'food:delete_product' productList.id%} ">Delete </a>
    </div>
  </div>
</div>

{% endblock %}

mysite/food/templates/food/product-delete.html
<form method="POST">
  {% csrf_token %}
  <h2>Are you sure you want to delete {{ product.product_name }}</h2>
  <button type="submit">Confirm</button>
</form>

mysite/food/templates/food/product-form.html
{% extends 'food/base.html'%} {% block body %}

<!-- create the form with post method  csrf prevents cross site scripting; provides security -->
<form method="POST">
  {% csrf_token %} {{form}}
  <button type="submit">Save</button>
</form>

{% endblock %}

mysite/users/templates/users/login.html
<form method="POST">
  {% csrf_token %} {{ form }}
  <button type="submit">Login</button>
</form>

mysite/users/templates/users/logout.html
<h1>You have been logged out</h1>

mysite/users/templates/users/profile.html
<h1>Username: {{ username }}</h1>
<img src="{{user.profile.image.url}}" />

mysite/users/templates/users/register.html
<form method="POST">
  {% csrf_token %} {{form}}
  <button type="submit">Signup</button>
</form>